name: HELLO WORLD
on: 
  - push
  #- pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: fail_step
        run: exit 1
      - name: echo-hello-world
        run: echo "Hola Mundo"
